version: '3.8'

services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc-server
    ports:
      - "50051:50051"
    networks:
      - grpc-network
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; channel = grpc.insecure_channel('localhost:50051'); channel.close()"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  grpc-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: grpc-client
    depends_on:
      grpc-server:
        condition: service_healthy
    networks:
      - grpc-network
    stdin_open: true
    tty: true
    environment:
      - GRPC_SERVER_HOST=grpc-server
      - GRPC_SERVER_PORT=50051

networks:
  grpc-network:
    driver: bridge